// Simboli meteo di MET Norway: legenda ufficiale (github.com/metno/weathericons,
// weather/legend.csv, letta il 10/10/2026), 41 simboli. Gli id restano come nella legenda,
// refusi compresi (lightssleet…, lightssnow…): sono quelli che l'API manda. Il suffisso
// _day/_night/_polartwilight si toglie prima di cercare qui.
export const simboli: Record<string, readonly [icona: string, descrizione: string]> = {
  clearsky: ['☀️', 'Sereno'],
  fair: ['🌤️', 'Poco nuvoloso'],
  partlycloudy: ['⛅', 'Parzialmente nuvoloso'],
  cloudy: ['☁️', 'Coperto'],
  fog: ['🌫️', 'Nebbia'],
  lightrainshowers: ['🌦️', 'Rovesci deboli'],
  rainshowers: ['🌦️', 'Rovesci'],
  heavyrainshowers: ['🌧️', 'Rovesci forti'],
  lightrainshowersandthunder: ['⛈️', 'Rovesci deboli con temporale'],
  rainshowersandthunder: ['⛈️', 'Rovesci con temporale'],
  heavyrainshowersandthunder: ['⛈️', 'Rovesci forti con temporale'],
  lightsleetshowers: ['🌨️', 'Rovesci di nevischio deboli'],
  sleetshowers: ['🌨️', 'Rovesci di nevischio'],
  heavysleetshowers: ['🌨️', 'Rovesci di nevischio forti'],
  lightssleetshowersandthunder: ['⛈️', 'Rovesci di nevischio deboli con temporale'],
  sleetshowersandthunder: ['⛈️', 'Rovesci di nevischio con temporale'],
  heavysleetshowersandthunder: ['⛈️', 'Rovesci di nevischio forti con temporale'],
  lightsnowshowers: ['🌨️', 'Rovesci di neve deboli'],
  snowshowers: ['🌨️', 'Rovesci di neve'],
  heavysnowshowers: ['❄️', 'Rovesci di neve forti'],
  lightssnowshowersandthunder: ['⛈️', 'Rovesci di neve deboli con temporale'],
  snowshowersandthunder: ['⛈️', 'Rovesci di neve con temporale'],
  heavysnowshowersandthunder: ['⛈️', 'Rovesci di neve forti con temporale'],
  lightrain: ['🌦️', 'Pioggia debole'],
  rain: ['🌧️', 'Pioggia'],
  heavyrain: ['🌧️', 'Pioggia forte'],
  lightrainandthunder: ['⛈️', 'Pioggia debole con temporale'],
  rainandthunder: ['⛈️', 'Pioggia con temporale'],
  heavyrainandthunder: ['⛈️', 'Pioggia forte con temporale'],
  lightsleet: ['🌨️', 'Nevischio debole'],
  sleet: ['🌨️', 'Nevischio'],
  heavysleet: ['🌨️', 'Nevischio forte'],
  lightsleetandthunder: ['⛈️', 'Nevischio debole con temporale'],
  sleetandthunder: ['⛈️', 'Nevischio con temporale'],
  heavysleetandthunder: ['⛈️', 'Nevischio forte con temporale'],
  lightsnow: ['🌨️', 'Neve debole'],
  snow: ['❄️', 'Neve'],
  heavysnow: ['❄️', 'Neve forte'],
  lightsnowandthunder: ['⛈️', 'Neve debole con temporale'],
  snowandthunder: ['⛈️', 'Neve con temporale'],
  heavysnowandthunder: ['⛈️', 'Neve forte con temporale'],
};
