services:
  unit:
    container_name: MonferrinaProject-unit
    build:
      context: .
      dockerfile: Dockerfile
      target: test-unit
  e2e:
    container_name: MonferrinaProject-e2e
    build:
      context: .
      dockerfile: Dockerfile
      target: test-e2e
